### ISSUE TITLE
Needle fails to download certificate on first request on AWS Lambda

### ISSUE THREAD

**Issue by ryanwitt** [ghdna/cognito-express#1]
Hey! I'm getting an error on AWS Lambda that I don't see on other platforms.

It looks like needle is failing to download the well-known certs on the first request, but I believe this only happens on lambda boot, and it succeeds on the second request:

```javascript
TypeError: Unable to generate certificate
    at needle.get (/var/task/node_modules/cognito-express/lib/strategy.js:60:23)
    at done (/var/task/node_modules/needle/lib/needle.js:437:14)
    at ClientRequest.had_error (/var/task/node_modules/needle/lib/needle.js:447:5)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketCloseListener (_http_client.js:285:9)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at _handle.close (net.js:497:12)
    at TCP.done [as _onclose] (_tls_wrap.js:332:7)
```

This error goes away when I replace needle with request.

**Comment by ghdna** [comment]
Thanks for letting me know. That's weird. I used needle because it seemed to be the simplest client. I've updated the package to use request & request-promise in 2.0.4 - let me know if this works better.

**Comment by ryanwitt** [comment]
Thanks, will test and let you know.
