### ISSUE TITLE
Getting socket hang up error randomly when deployed on lambda

### ISSUE THREAD

**Issue by MohitNaik-Bit** [ghdna/cognito-express#26]
This issue occurs very randomly and is automatically resolved after few mins. I have attached the cloudwatch logs below for reference.

> Unable to generate certificate due to 
> RequestError: Error: socket hang up
> at /var/task/node_modules/cognito-express/lib/strategy.js:41:23
> at tryCatcher (/var/task/node_modules/bluebird/js/release/util.js:16:23)
> at Promise._settlePromiseFromHandler (/var/task/node_modules/bluebird/js/release/promise.js:512:31)
> at Promise._settlePromise (/var/task/node_modules/bluebird/js/release/promise.js:569:18)
> at Promise._settlePromise0 (/var/task/node_modules/bluebird/js/release/promise.js:614:10)
> at Promise._settlePromises (/var/task/node_modules/bluebird/js/release/promise.js:690:18)
> at _drainQueueStep (/var/task/node_modules/bluebird/js/release/async.js:138:12)
> at _drainQueue (/var/task/node_modules/bluebird/js/release/async.js:131:9)
> at Async._drainQueues (/var/task/node_modules/bluebird/js/release/async.js:147:5)
> at Immediate.Async.drainQueues (/var/task/node_modules/bluebird/js/release/async.js:17:14)
> at runCallback (timers.js:794:20)
> at tryOnImmediate (timers.js:752:5)
> at processImmediate [as _immediateCallback] (timers.js:729:5)

**Comment by rzagorski** [comment]
I found the same issue in our environment. Its not minutes but hours but current quick "dummy" solution is to restart lambda

**Comment by jcardus** [comment]
Same problem here...
