### ISSUE TITLE
Runtime.UnhandledPromiseRejection

### ISSUE THREAD

**Issue by ohadperry** [ghdna/cognito-express#40]
```
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError: Unable to generate certificate due to \nRequestError: Error: Client network socket disconnected before secure TLS connection was established",
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "Unable to generate certificate due to \nRequestError: Error: Client network socket disconnected before secure TLS connection was established",
        "stack": [
            "TypeError: Unable to generate certificate due to ",
            "RequestError: Error: Client network socket disconnected before secure TLS connection was established",
            "    at /var/task/node_modules/cognito-express/lib/strategy.js:42:23",
            "    at bound (domain.js:427:14)",
            "    at runBound (domain.js:440:12)",
            "    at tryCatcher (/var/task/node_modules/bluebird/js/release/util.js:16:23)",
            "    at Promise._settlePromiseFromHandler (/var/task/node_modules/bluebird/js/release/promise.js:547:31)",
            "    at Promise._settlePromise (/var/task/node_modules/bluebird/js/release/promise.js:604:18)",
            "    at Promise._settlePromise0 (/var/task/node_modules/bluebird/js/release/promise.js:649:10)",
            "    at Promise._settlePromises (/var/task/node_modules/bluebird/js/release/promise.js:725:18)",
            "    at _drainQueueStep (/var/task/node_modules/bluebird/js/release/async.js:93:12)",
            "    at _drainQueue (/var/task/node_modules/bluebird/js/release/async.js:86:9)",
            "    at Async._drainQueues (/var/task/node_modules/bluebird/js/release/async.js:102:5)",
            "    at Immediate.Async.drainQueues [as _onImmediate] (/var/task/node_modules/bluebird/js/release/async.js:15:14)",
            "    at processImmediate (internal/timers.js:456:21)",
            "    at process.topLevelDomainCallback (domain.js:138:15)",
            "    at process.callbackTrampoline (internal/async_hooks.js:118:14)"
        ]
    },
    "promise": {
        "isFulfilled": false,
        "isRejected": true,
        "rejectionReason": {
            "errorType": "TypeError",
            "errorMessage": "Unable to generate certificate due to \nRequestError: Error: Client network socket disconnected before secure TLS connection was established",
            "stack": [
                "TypeError: Unable to generate certificate due to ",
                "RequestError: Error: Client network socket disconnected before secure TLS connection was established",
                "    at /var/task/node_modules/cognito-express/lib/strategy.js:42:23",
                "    at bound (domain.js:427:14)",
                "    at runBound (domain.js:440:12)",
                "    at tryCatcher (/var/task/node_modules/bluebird/js/release/util.js:16:23)",
                "    at Promise._settlePromiseFromHandler (/var/task/node_modules/bluebird/js/release/promise.js:547:31)",
                "    at Promise._settlePromise (/var/task/node_modules/bluebird/js/release/promise.js:604:18)",
                "    at Promise._settlePromise0 (/var/task/node_modules/bluebird/js/release/promise.js:649:10)",
                "    at Promise._settlePromises (/var/task/node_modules/bluebird/js/release/promise.js:725:18)",
                "    at _drainQueueStep (/var/task/node_modules/bluebird/js/release/async.js:93:12)",
                "    at _drainQueue (/var/task/node_modules/bluebird/js/release/async.js:86:9)",
                "    at Async._drainQueues (/var/task/node_modules/bluebird/js/release/async.js:102:5)",
                "    at Immediate.Async.drainQueues [as _onImmediate] (/var/task/node_modules/bluebird/js/release/async.js:15:14)",
                "    at processImmediate (internal/timers.js:456:21)",
                "    at process.topLevelDomainCallback (domain.js:138:15)",
                "    at process.callbackTrampoline (internal/async_hooks.js:118:14)"
            ]
        }
    },
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError: Unable to generate certificate due to ",
        "RequestError: Error: Client network socket disconnected before secure TLS connection was established",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:327:22)",
        "    at process.EventEmitter.emit (domain.js:483:12)",
        "    at eventToObjectGenerator.promiseCreated (/var/task/node_modules/bluebird/js/release/debuggability.js:258:33)",
        "    at activeFireEvent (/var/task/node_modules/bluebird/js/release/debuggability.js:301:44)",
        "    at fireRejectionEvent (/var/task/node_modules/bluebird/js/release/debuggability.js:703:14)",
        "    at Promise._notifyUnhandledRejection (/var/task/node_modules/bluebird/js/release/debuggability.js:90:9)",
        "    at Timeout.unhandledRejectionCheck [as _onTimeout] (/var/task/node_modules/bluebird/js/release/debuggability.js:39:25)",
        "    at listOnTimeout (internal/timers.js:549:17)",
        "    at processTimers (internal/timers.js:492:7)"
    ]
}


```

enviroment:

provider:
  name: aws
  runtime: nodejs12.x
`lambda `

**Comment by jcardus** [comment]
Im having the same error

**Comment by jcardus** [comment]
2020-12-10T14:31:56.852Z	2f303802-9292-42ef-88ea-6031dc709105	ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "Unable to generate certificate due to \nRequestError: Error: Client network socket disconnected before secure TLS connection was established",
    "stack": [
        "TypeError: Unable to generate certificate due to ",
        "RequestError: Error: Client network socket disconnected before secure TLS connection was established",
        "    at /var/task/node_modules/cognito-express/lib/strategy.js:42:23",
        "    at tryCatcher (/var/task/node_modules/bluebird/js/release/util.js:16:23)",
        "    at Promise._settlePromiseFromHandler (/var/task/node_modules/bluebird/js/release/promise.js:547:31)",
        "    at Promise._settlePromise (/var/task/node_modules/bluebird/js/release/promise.js:604:18)",
        "    at Promise._settlePromise0 (/var/task/node_modules/bluebird/js/release/promise.js:649:10)",
        "    at Promise._settlePromises (/var/task/node_modules/bluebird/js/release/promise.js:725:18)",
        "    at _drainQueueStep (/var/task/node_modules/bluebird/js/release/async.js:93:12)",
        "    at _drainQueue (/var/task/node_modules/bluebird/js/release/async.js:86:9)",
        "    at Async._drainQueues (/var/task/node_modules/bluebird/js/release/async.js:102:5)",
        "    at Immediate.Async.drainQueues [as _onImmediate] (/var/task/node_modules/bluebird/js/release/async.js:15:14)",
        "    at processImmediate (internal/timers.js:461:21)"
    ]
}

**Comment by jcardus** [comment]
Looking at the code looks like the error is empty

**Comment by s10mcow** [comment]
+1 same issue

**Comment by swanandvk** [comment]
+1 having the same , whats the root cause of this any intel ?

**Comment by jcardus** [comment]
I had this again today. I gave more memory to the lambda function, it was 128, it's now 1024. It's a shot in the dark...

**Comment by dalumiller** [comment]
+1 same issue; any solutions?

**Comment by toolsadminatl2it** [comment]
We are facing this issue very frequently. Is there any solution to this? Is it because of the cold start in the lambda environment? We have noticed in our error monitoring tool that all the transactions with this issue had the cold start.

**Comment by andreme** [comment]
This is a wrapper that retries downloading the certificates if it fails for some reason:
```js
let cognitoExpress;
async function cogValidateToken(token, retryCounter = 0) {

	if (!cognitoExpress) {
		cognitoExpress = new CognitoExpress({
			region: 'SET',
			cognitoUserPoolId: 'SET',
			tokenUse: 'access',
		});
	}

	try {
		return await cognitoExpress.validate(token);
	} catch (e) {
		if ((retryCounter < 25) && String(e.message).startsWith('Unable to generate certificate due to')) {
			console.error(e);
			cognitoExpress = null;
			return cogValidateToken(token, retryCounter + 1);
		}

		throw e;
	}
}
```
Call with 
```js
const jwt = await cogValidateToken(token);
```

**Comment by mekane** [comment]
I'm running into this in my CI/CD where the VM doesn't have network access. Line 54 of strategy.js is throwing with no catch and I can't find a way to quiet it down.

**Comment by ghdna** [comment]
Ok lemme take a look
